# Generated by Django 4.2.26 on 2025-11-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.tienda'),
        ),
        migrations.AlterField(
            model_name='resenadeproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='resenadetienda',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.tienda'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='artesano',
            field=models.OneToOneField(limit_choices_to={'rol': 'artesano'}, on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
    ]
