# Generated by Django 4.2.26 on 2025-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_favorito_producto_alter_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('CA', 'Cancelado'), ('R', 'Rechazado')], default='P', max_length=2),
        ),
    ]
