# Generated by Django 4.2.26 on 2025-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_activo_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('reseña', 'Reseña'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
