# Generated by Django 4.2.26 on 2025-12-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conversacion_perfil_documento_identidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
