# Generated by Django 5.0 on 2025-11-23 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0004_alter_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='verificado',
            new_name='correo_validado',
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
